# h2-console
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  # db url
  datasource:
    url: jdbc:h2:mem:database

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema/schema.sql
